### ISSUE TITLE
mitch_report fails if an absoulte path is given as outfile

### ISSUE THREAD

**Issue by Christian-Heyer** [markziemann/mitch#13]
When I attempt to run `mitch_report` using an absolute path for outfile, it will fail with an error message like:
```r
> data(resExample)
> mitch_report(resExample, '/desktop-home/heyer/outres2.html')
Error in file(file, "wb") : cannot open the connection
In addition: Warning message:
In file(file, "wb") :
  cannot open file '/tmp/Rtmpv71mKa//desktop-home/heyer/outres2.RDataTmp': No such file or directory
Warning message:
In file.remove(outfile) :
  cannot remove file '/tmp/Rtmpv71mKa//desktop-home/heyer/outres2.RDataTmp', reason 'No such file or directory'
```

I guess this is somehow related to how the temporary file paths are created from the outfile in the `mitch_report` function.
I don't know if this is somehow related to #10, but after installing the package from GitHub directly i still ran into this issue.

**Comment by markziemann** [comment]
@Christian-Heyer Thanks for raising this issue. I can reproduce it, so I will start work on a patch.

**Comment by markziemann** [comment]
Hi Christian, I've pushed a patch, could you install from GitHub and give it a try? Thanks

**Comment by Christian-Heyer** [comment]
Hi Mark, sorry for the delay, but I was able to try out the new version and the bug is fixed.
Thanks for the quick fix.
