### ISSUE TITLE
Enrichment of very simillar samples

### ISSUE THREAD

**Issue by fischerstm** [markziemann/mitch#27]
Currently, I´m using two samples which are very simillar and I ask myself how to test those adequate (also after reading your current paper in PLOS CompBiol). So, there are several questions I have:

- The samples are RNA-seqs of 2 different knock-down experiments using the same Ctrl; experiments were performed in parallel. 

- Normally using GSEA I rather prefer to compare only the knock-downs against the controls, as the effect of the knock-downs are only valid against the controls. Having very simillar results I fear that "using knock-down 1" vs "knock down 2" in a weighted gsea with gene set permutation, signal2noise metric etc leads to results which are overrated. Do you think GSEA statsitical testing is adequate for this kind of testing?

- As I use also self-generated gene sets with GSEA: I think using self-genearted gene sets should always be done with sufficient background -meaning embedded in gene set collections with a adequate size. Do you have any experience about that?

- Comparing the knock-down with each other I normally use mitch with several ranked diff.expressed gene list (knock-down 1 vs Ctrl tested against knock-down 2 vs Ctrl ). These contrasts are to simillar so that I do not receive a valid result by mitch using e.g. GO BP or simillar. As we are interested in a distinct biological function I ask if it is worth and appropriate to test only a rather low number of self generated gene sets to evaluate a difference or simillarity: not 1000 but rather dozens of gene sets?

**Comment by markziemann** [comment]
>The samples are RNA-seqs of 2 different knock-down experiments using the same Ctrl; experiments were performed in parallel.

That sounds okay. I'm assuming you have n>2 replicates per sample group? Using edgeR or DESeq2 for DE analysis?

>Normally using GSEA I rather prefer to compare only the knock-downs against the controls, as the effect of the knock-downs are only valid against the controls. Having very simillar results I fear that "using knock-down 1" vs "knock down 2" in a weighted gsea with gene set permutation, signal2noise metric etc leads to results which are overrated. Do you think GSEA statsitical testing is adequate for this kind of testing?

With regard to using GSEA, I would first consult the PCA plot. If the control and two knock down groups are all separated into clusters then it would be fine to run GSEA to determine enrichment for round robin comparison. Eg: ctrl vs kd1, ctrl vs kd2 and kd1 vs kd2. If you were to use the mitch package, then you would import the DESeq2 results from the two contrasts (ctrl vs kd1 and ctrl vs kd2) and perform a 2D enrichment analysis. This will show the gene sets with concordant regulation as well as the ones with discordant regulation.

>As I use also self-generated gene sets with GSEA: I think using self-genearted gene sets should always be done with sufficient background -meaning embedded in gene set collections with a adequate size. Do you have any experience about that?

Self generated gene sets are awesome. Typically this sort of analysis is conducted with a set of apriori hypotheses, meaning that it is okay if there are relatively few gene sets considered in any single custom GSEA run. If you are testing just one gene set with GSEA, it is okay to simply use the nominal p-value. I don't think it is necessary to embed the custom gene set in a larger collection.

>Comparing the knock-down with each other I normally use mitch with several ranked diff.expressed gene list (knock-down 1 vs Ctrl tested against knock-down 2 vs Ctrl ). These contrasts are to simillar so that I do not receive a valid result by mitch using e.g. GO BP or simillar. As we are interested in a distinct biological function I ask if it is worth and appropriate to test only a rather low number of self generated gene sets to evaluate a difference or simillarity: not 1000 but rather dozens of gene sets?

If you are importing the full DESeq2 results into mitch for these two contrasts, you should be getting some results. Can you provide a bit of detail as to the objects you are putting into mitch and what error/warning/output message/data you received? Mitch, being a functional class scoring tool, requires the full output of the DE analysis, typically 10,000 to 20,000 genes. It doesn't analyse lists of DE genes, like over-representation analysis. If you are receiving FDR values > 0.05, then you may be dealing with null data.

With regards to your question about testing against one or a few gene sets only - I think this is okay if you have strong apriori reason to believe these gene sets are altered. With that in mind, you need to report the results responsibly and avoid the temptation for [Harking](https://en.wikipedia.org/wiki/HARKing).
