### ISSUE TITLE
Pre-filtering of results?

### ISSUE THREAD

**Issue by dakota-hawkins** [markziemann/mitch#38]
Hi there!

Thanks so much for the package. I've found it incredibly useful, intuitive, and extremely well documented -- really appreciate all the work you've put into it and making it so accessible!

I just had a quick question: should I be filtering DE results for significance before feeding the tables into `mitch_import()`? 

Obviously this is quite common in many of enrichment/ORA analysis tools, but it seems the `D` score calculated by `mitch` may essentially account for this when combined with the `p.adjustMANOVA` in the final results. 

Thanks again for the package and any insight you can provide!

Dakota

**Comment by markziemann** [comment]
Hi Dakota,
Thanks for your message. `mitch` and other functional class scoring based methods require the full list of detected genes. Therefore you don't want to filter for significance before running mitch.

**Comment by dakota-hawkins** [comment]
Thanks, Mark! Appreciate the quick response, and again, appreciate your work here. `mitch` is a really great tool!
